### ISSUE TITLE
Ensure-RegistryValue did not work due to authorization access

### ISSUE THREAD

**Issue by pcamelio** [Inedo/inedox-windows#45]
Hello

I ran the following Plan
   Windows::Ensure-RegistryValue
```
    (
        Name: AllowTelemetry,
        Value: 0,
        Kind: DWord,
        Hive: LocalMachine,
        Key: SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\DataCollection
    );
```
And I have got the following error 
```
Unhandled exception: System.UnauthorizedAccessException: Impossible d'écrire dans la clé de Registre.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Inedo.Agents.InedoAgentClientBase.<SendMessageAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Inedo.Agents.InedoAgentClientBase.<ExecuteCommandAsync>d__26`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Inedo.Otter.Service.PlanExecuter.OtterPlanExecuter.<PerformExecution>d__49.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Inedo.Otter.Service.PlanExecuter.OtterPlanExecuter.<Inedo-ExecutionEngine-Executer-IExecutionHostEnvironment-ExecuteActionAsync>d__53.MoveNext()
```

The agent - 2.0.8 -  is running with Windows account (local admin rights). 
I have the same problem on the otter server itself. - setup without the Agent -

- Otter server : Windows 2016 Datacenter Core with IIS 10. 
- OtterpAppPool is running under the windows account.
- Otter Client : Windows 2016 Datacenter Core

I modified the registry authorization, but the problem is still present.

I try with an other registry value 
```
Windows::Ensure-RegistryValue
(
    Name: EnableRemoteManagement,
    Value: 1,
    Kind: DWord,
    Hive: LocalMachine,
    Key: SOFTWARE\Microsoft\WebManagement\Server
);
```unsuccessfully

**Comment by pcamelio** [comment]
I have found that I made a big mistake in the syntax.
```
Windows::Ensure-RegistryValue
(
    Name: EnableRemoteManagement,
    Value: 1,
    Kind: DWord,
    Hive: LocalMachine,
    Key: SOFTWARE\Microsoft\WebManagement\Server
);
```
have to be write:
```
(
    Name: EnableRemoteManagement,
    Value: 1,
    Kind: DWord,
    Hive: LocalMachine,
    Key: SOFTWARE\Microsoft\WebManagement\Server\EnableRemoteManagement
);
```

**Comment by pcamelio** [comment]
You should write documentation in French :)
